spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/bhhx?characterEncoding=utf8&useSSL=false
    password: newsys4weilai$
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8088
